// Auto-extracted verbatim: feed text templates + inline SVG constants.
export const HEART_SVG='<svg viewBox="0 0 24 24" class="fd-ic"><path d="M12 21s-7-4.5-9.5-8.5C.8 9.5 2 6 5.2 6c1.9 0 3 1 3.8 2 .8-1 1.9-2 3.8-2 3.2 0 4.4 3.5 2.7 6.5C19 16.5 12 21 12 21z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>';
export const REPLY_SVG='<svg viewBox="0 0 24 24" class="fd-ic"><path d="M21 12a8 8 0 0 1-8 8H7l-4 3v-3a8 8 0 1 1 18-8z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg>';
export const SHARE_SVG='<svg viewBox="0 0 24 24" class="fd-ic"><path d="M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7M16 6l-4-4-4 4M12 2v13" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
export const RT_SVG='<svg viewBox="0 0 24 24" class="fd-ic"><path d="M7 7h9l-2.2-2.2M17 17H8l2.2 2.2" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/><path d="M16 7.2v6M8 16.8v-6" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>';
export const VIEW_SVG='<svg viewBox="0 0 24 24" class="fd-ic"><path d="M4 20V11M9 20V5M14 20v-8M19 20V8" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';
export const VTICK='<svg viewBox="0 0 24 24" class="vtick"><path d="M12 1.5l2.3 1.7 2.85.18.95 2.67 2.3 1.72-.86 2.73.86 2.73-2.3 1.72-.95 2.67-2.85.18L12 21.5l-2.3-1.7-2.85-.18-.95-2.67-2.3-1.72.86-2.73-.86-2.73 2.3-1.72.95-2.67 2.85-.18z" fill="#1d9bf0"/><path d="M8.6 12.2l2.3 2.3 4.4-4.7" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';
export const FD_ASSETS=['Gold','Bitcoin','Nasdaq','EUR/USD','Tesla','Silver','Oil','Solana','GBP/JPY','Ethereum'];
export const FD_THT=['sizing down into the data, no heroes today','patience is the whole edge honestly','green week, boring trades, exactly how i like it','cut a loser early for once \u2014 growth','the market does not care about your bias','risk first, profit second, every time','took the day off, best trade i made all week'];
export const FD_IDEA_R=['reclaim of the range high','failed breakdown into momentum','liquidity sweep into demand','trend-day continuation','daily flip back into supply','bounce off the weekly level'];
export const FD_ANA=['{a} coiling under resistance \u2014 break or fade, no middle ground. Watching the close.','{a} bid all session, every dip bought instantly. Strength until proven otherwise.','careful chasing {a} up here, stretched from the mean and volume is thinning.','{a} reclaiming the level it lost last week. If it holds there is room to run.','{a} range-bound and choppy \u2014 sitting on hands until it picks a side.'];
export const FD_CALL=['who wants to run it? {w} window, demo accounts, higher return takes the pot.','open challenge \u2014 {w} battle, anyone Sharp rank or above. let us go.','bored. someone battle me. {w} window, {p} pot, first to accept it.'];
export const FD_ORDER=['thought','media','callout','result','thought','callout','media','result','thought','callout','unlock','media','thought','result','callout','media','thought','result','thought','callout'];
export const FD_BLIVE=['{a} vs {b} is must-watch right now','my money on {a} here','this one is close \ud83d\udc40','{a} pulling away from {b} ngl','tuning into {a} v {b}, clip it','{a} v {b} \u2014 whoever wins is him'];
export const FD_RESW=['Took the battle vs {o} and ran it.','Beat {o}. GG.','Closed out {o} \u2014 clean.','Ran it back on {o}, won comfortably.','{o} put up a fight. Still took it.','Battle vs {o} done. Easy.'];
export const FD_MEDIA=['my screen this morning','the chart that paid today','clip from the session','how it closed \ud83d\udcc8','live PnL right now','caught the whole move','posting this before someone says i made it up'];
export const THOUGHTS=['Patience paid again — waited days for {a} to come to my level. Textbook.','Risk management isn\'t sexy but it\'s why I\'m still here.','Took partial profit on {a}, letting the rest run to target.','If you\'re revenge trading, close the laptop. Learned that one the hard way.','Comp leaderboard is brutal this week. Love it.','Cut a loser early today. Process over ego, every time.','Watching {a} coil up. Big move incoming.','Won my Arena battle today — GGs to a tough opponent.','Boring week, small gains, exactly how I like it.','New account high. Onwards.','{a} is the cleanest setup on my board right now.','Sized down this week. When in doubt, trade smaller.'];
export const THT_ASSETS=['Gold','BTC','EUR/USD','US100','TSLA','ETH','GBP/JPY','Silver'];
