// Partner/affiliate portal, ported from the prototype. `affiliateHTML(S)` returns the
// full view markup; `drawAffChart` renders the earnings canvas.
import { fmt, money, LT } from './format.js'
import { WORLD_CHORO } from './_world.js'

export function affSeries(S) { const P = S.affil.chartPeriod || 'monthly'; return (S.affil.series && S.affil.series[P]) ? S.affil.series[P] : { v: S.affil.earn, l: ['J', 'A', 'S', 'O', 'N', 'D', 'J', 'F', 'M', 'A', 'M', 'J'] } }
function affGeo(S, c) { if (!c) return null; const n = affSeries(S).v.length; const w = c.clientWidth, h = c.clientHeight || 240; const padL = 46, padB = 20, padT = 12, gw = w - padL - 8, gh = h - padB - padT; return { w, h, padL, padT, gw, gh, bw: gw / n, n } }

function rrect(ctx, x, y, w, h, r) { r = Math.min(r, w / 2, h / 2); ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r); ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r); ctx.closePath() }

export function drawAffChart(S, c) {
  if (!c) return; const dpr = window.devicePixelRatio || 1
  const w = c.clientWidth, h = c.clientHeight || 240; if (!w) return; c.width = w * dpr; c.height = h * dpr
  const ctx = c.getContext('2d'); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, w, h)
  const SR = affSeries(S), d = SR.v, lab = SR.l || [], n = d.length, mx = Math.max.apply(null, d) * 1.18 || 1
  const cum = []; let run = 0; d.forEach((v) => { run += v; cum.push(run) }); const tot = run || 1
  const G = affGeo(S, c), padL = G.padL, padT = G.padT, gw = G.gw, gh = G.gh, bw = G.bw
  const gl = LT() ? '#eceef1' : '#15171a', axt = LT() ? '#9498a1' : '#565b62'
  ctx.font = '9px JetBrains Mono'; ctx.textBaseline = 'middle'; ctx.textAlign = 'right'
  for (let g = 0; g <= 3; g++) { const yy = padT + gh * g / 3, val = mx - mx * g / 3; ctx.strokeStyle = gl; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(padL, yy); ctx.lineTo(padL + gw, yy); ctx.stroke(); ctx.fillStyle = axt; ctx.fillText('£' + Math.round(val / 100) / 10 + 'k', padL - 6, yy) }
  const bwi = Math.max(2, Math.min(22, bw * 0.6))
  d.forEach((v, i) => { const x = padL + i * bw + bw / 2, bh = (v / mx) * gh, y = padT + gh - bh; const grad = ctx.createLinearGradient(0, y, 0, padT + gh); grad.addColorStop(0, '#9a7cff'); grad.addColorStop(1, '#7c5cff'); ctx.fillStyle = grad; rrect(ctx, x - bwi / 2, y, bwi, bh, 3); ctx.fill() })
  ctx.beginPath(); d.forEach((v, i) => { const x = padL + i * bw + bw / 2, y = padT + gh - (cum[i] / tot) * gh; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y) })
  ctx.lineTo(padL + (n - 1) * bw + bw / 2, padT + gh); ctx.lineTo(padL + bw / 2, padT + gh); ctx.closePath()
  const ag = ctx.createLinearGradient(0, padT, 0, padT + gh); ag.addColorStop(0, 'rgba(127,179,154,.13)'); ag.addColorStop(1, 'rgba(127,179,154,0)'); ctx.fillStyle = ag; ctx.fill()
  ctx.strokeStyle = LT() ? '#16a878' : '#7fb39a'; ctx.lineWidth = 2; ctx.lineJoin = 'round'; ctx.beginPath(); d.forEach((v, i) => { const x = padL + i * bw + bw / 2, y = padT + gh - (cum[i] / tot) * gh; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y) }); ctx.stroke()
  ctx.fillStyle = axt; ctx.textAlign = 'center'; const step = n > 14 ? Math.ceil(n / 6) : 1
  for (let i2 = 0; i2 < n; i2++) { if (i2 % step === 0 || i2 === n - 1) ctx.fillText((lab[i2] || '').toString(), padL + i2 * bw + bw / 2, h - 7) }
}

export function affiliateHTML(S) {
  const A = S.affil, conv = A.clicks ? A.signups / A.clicks * 100 : 0, tab = A.tab || 'overview'
  const shareText = encodeURIComponent('I’m competing on Tradr — licensed trading competitions with real prize pools. Join with my link:')
  const linkEnc = encodeURIComponent('https://' + A.link)
  const st = (l, v, sub, cls) => '<div class="aff-stat"><div class="aff-stat-l">' + l + '</div><div class="aff-stat-v ' + (cls || '') + '">' + v + '</div>' + (sub ? '<div class="aff-stat-s">' + sub + '</div>' : '') + '</div>'
  const hero = '<div class="aff-hero"><div class="aff-hero-l"><div class="aff-eyebrow">Partner programme</div>' +
    '<div class="aff-h">Earn 20% — for the lifetime of every client</div>' +
    '<div class="aff-sub">Share your link. When someone you refer joins Tradr, you earn <b>20% of Tradr’s net revenue</b> from them — for as long as they keep competing. One flat rate, no tiers, paid every month.</div>' +
    '<div class="aff-link"><span class="aff-link-ic">↗</span><span class="aff-link-u">' + A.link + '</span><button class="aff-copy" data-affcopy>Copy link</button></div>' +
    '<div class="aff-share"><button class="aff-sh x" data-href="https://twitter.com/intent/tweet?text=' + shareText + '&url=' + linkEnc + '">Share on X</button>' +
    '<button class="aff-sh wa" data-href="https://wa.me/?text=' + shareText + '%20' + linkEnc + '">WhatsApp</button>' +
    '<button class="aff-sh" data-affcopy>Copy code · ' + A.code + '</button></div></div>' +
    '<div class="aff-hero-r"><div class="aff-rate-v">20%</div><div class="aff-rate-l">flat lifetime revenue share</div><div class="aff-rate-sub">paid monthly · GBP or USDC</div></div></div>'
  const TABS = [['overview', 'Overview'], ['network', 'Network'], ['clients', 'Clients'], ['earnings', 'Earnings'], ['assets', 'Assets']]
  const tabbar = (S.appMode === 'partner') ? '' : ('<div class="aff-tabbar">' + TABS.map((t) => '<button class="aff-tabb' + (tab === t[0] ? ' on' : '') + '" data-afftab="' + t[0] + '">' + t[1] + '</button>').join('') + '</div>')
  const earningsCard = () => { const per = A.chartPeriod || 'monthly'; const tg = [['daily', 'Daily'], ['monthly', 'Monthly'], ['quarterly', 'Quarterly'], ['annual', 'Annual']].map((x) => '<button class="affch-b' + (per === x[0] ? ' on' : '') + '" data-affchart="' + x[0] + '">' + x[1] + '</button>').join(''); return '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Earnings</div><div class="affch-tog">' + tg + '</div></div><div class="affch-wrap"><canvas id="affChart"></canvas><div class="affch-tip" id="affTip"></div></div></div>' }
  const milestonesCard = () => { const m = A.milestone, prog = Math.max(4, Math.min(100, (A.lifetime - m.prev) / (m.next - m.prev) * 100)); return '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Partner status</div><span class="aff-pill on">Rank #' + A.rank + '</span></div><div class="gam-grid"><div class="gam-cell"><div class="gam-n">#' + A.rank + '</div><div class="gam-l">of ' + A.totalPartners.toLocaleString() + '</div></div><div class="gam-cell"><div class="gam-n">' + A.streak + 'd</div><div class="gam-l">active streak</div></div><div class="gam-cell"><div class="gam-n">' + money(A.lifetime) + '</div><div class="gam-l">earned</div></div></div><div class="gam-ms"><div class="gam-ms-h"><span>Next milestone · ' + m.label + '</span><span class="mono">' + money(m.next - A.lifetime) + ' to go</span></div><div class="aff-prog-bar"><span style="width:' + prog + '%"></span></div></div><div class="gam-badges">' + A.badges.map((b) => '<span class="gam-badge">✓ ' + b + '</span>').join('') + '</div></div>' }
  const funnel = () => { const ff = A.funnel, steps = [['Clicks', ff.clicks], ['Signups', ff.signups], ['Funded', ff.funded], ['Active', ff.active]], mx = ff.clicks || 1; return '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Conversion funnel</div></div><div class="funnel">' + steps.map((x, i) => { const w = Math.max(7, x[1] / mx * 100), drop = i > 0 ? (x[1] / steps[i - 1][1] * 100).toFixed(0) + '%' : ''; return '<div class="fn-row"><span class="fn-l">' + x[0] + '</span><div class="fn-bar"><span style="width:' + w + '%"></span><b>' + x[1].toLocaleString() + '</b></div><span class="fn-d">' + drop + '</span></div>' }).join('') + '</div></div>' }
  const heatmap = () => { const d = A.signupHeat, mx = Math.max.apply(null, d) || 1, tot = d.reduce((a, b) => a + b, 0); const cells = d.map((v) => { const lv = v === 0 ? 0 : Math.max(1, Math.min(4, Math.ceil(v / mx * 4))); return '<span class="heat-c l' + lv + '" title="' + v + ' signups"></span>' }).join(''); return '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Signups over time · last 17 weeks</div><span class="dim" style="font-size:11px">' + tot + ' signups</span></div><div class="heat-wrap"><div class="heat-grid">' + cells + '</div></div><div class="heat-leg"><span>Less</span><span class="heat-c l0"></span><span class="heat-c l1"></span><span class="heat-c l2"></span><span class="heat-c l3"></span><span class="heat-c l4"></span><span>More</span></div></div>' }
  const worldMap = () => { const mx = Math.max.apply(null, A.regions.map((r) => r.c)) || 1; const leg = [['0', 'l0'], ['1–9', 'l1'], ['10–24', 'l2'], ['25–49', 'l3'], ['50–79', 'l4'], ['80+', 'l5']].map((x) => '<span class="wm-sw"><i class="wmi ' + x[1] + '"></i>' + x[0] + '</span>').join(''); return '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Signups by geography</div><span class="dim" style="font-size:11px">live world heatmap</span></div><div class="wmap"><svg viewBox="0 0 1000 480" preserveAspectRatio="xMidYMid meet" class="wmsvg">' + WORLD_CHORO + '</svg></div><div class="wm-legend"><span>Signups</span>' + leg + '</div><div class="reg" style="margin-top:14px">' + A.regions.map((r) => '<div class="reg-row"><span class="reg-n">' + r.n + '</span><div class="reg-bar"><span style="width:' + (r.c / mx * 100) + '%"></span></div><span class="reg-v mono">' + r.c + '</span></div>').join('') + '</div></div>' }

  let body
  if (tab === 'network') {
    const statusCard = '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Player status</div></div><div class="statgrid">' + [['Active', A.active, 'on'], ['Trial', A.trial, 'tr'], ['Dormant', A.dormant, 'dm'], ['Churned', A.churned, 'ch']].map((x) => '<div class="statcell ' + x[2] + '"><div class="statn">' + x[1] + '</div><div class="statl">' + x[0] + '</div></div>').join('') + '</div></div>'
    body = '<div class="aff-stats n4">' + st('Players under you', A.signups + '', 'across all tiers') + st('Active now', A.active + '', Math.round(A.active / A.signups * 100) + '% of base') + st('Their winnings', money(A.clientWon), 'won in competitions', 'up') + st('Their spend', money(A.clientSpend), 'lifetime, all clients') + '</div>' +
      worldMap() + '<div class="aff-grid2">' + funnel() + statusCard + '</div>' +
      '<div class="aff-grid2"><div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Top players under you</div><span class="dim" style="font-size:11px">by winnings</span></div><table class="aff-tab"><thead><tr><th>Player</th><th>Region</th><th class="r">Won</th><th class="r">Spend</th></tr></thead><tbody>' + A.refs.slice().sort((a, b) => b.won - a.won).slice(0, 6).map((r) => '<tr><td class="mono">' + r.h + '</td><td class="dim">' + r.region + '</td><td class="r mono up">' + money(r.won) + '</td><td class="r mono">' + money(r.spend) + '</td></tr>').join('') + '</tbody></table></div>' +
      '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Sub-affiliates</div><span class="dim" style="font-size:11px">' + A.overrideRate + '% override</span></div><table class="aff-tab"><thead><tr><th>Partner</th><th class="r">Clients</th><th class="r">They earned</th><th class="r">Your ' + A.overrideRate + '%</th></tr></thead><tbody>' + A.subAffs.map((x) => '<tr><td class="mono">' + x.h + '</td><td class="r mono">' + x.clients + '</td><td class="r mono">' + money(x.earned) + '</td><td class="r mono up">' + money(x.override) + '</td></tr>').join('') + '</tbody></table><button class="aff-sh" data-affcopy style="margin-top:10px">Invite sub-affiliates</button></div></div>' +
      '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Recent activity</div><span class="live"><span class="b"></span>Live</span></div><div class="afeed">' + A.activity.map((a) => '<div class="afeed-row"><span class="afeed-d ' + a.t + '"></span><span class="afeed-x">' + a.x + '</span><span class="afeed-t mono">' + a.ago + '</span></div>').join('') + '</div></div>'
  } else if (tab === 'clients') {
    body = '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Referred clients</div><button class="pf-share" data-toast="Full client list exported">Export CSV</button></div><div class="aff-scroll"><table class="aff-tab aff-tab-wide"><thead><tr><th>Client</th><th>Region</th><th>Joined</th><th>Status</th><th class="r">Trades</th><th class="r">Their winnings</th><th class="r">Lifetime spend</th><th class="r">Your 20%</th><th class="r">Last active</th></tr></thead><tbody>' + A.refs.map((r) => { const sc = r.status === 'active' ? 'on' : r.status === 'trial' ? 'tr' : 'ch'; return '<tr><td class="mono">' + r.h + '</td><td class="dim">' + r.region + '</td><td class="dim mono">' + r.joined + 'd ago</td><td><span class="aff-pill ' + sc + '">' + r.status.charAt(0).toUpperCase() + r.status.slice(1) + '</span></td><td class="r mono">' + r.trades + '</td><td class="r mono up">' + money(r.won) + '</td><td class="r mono">' + money(r.spend) + '</td><td class="r mono up">' + money(r.comm) + '</td><td class="r dim mono">' + r.last + '</td></tr>' }).join('') + '</tbody></table></div><div class="aff-note" style="margin-top:14px">Per-client spend is shown for your records — in production this is aggregated to protect client privacy.</div></div>'
  } else if (tab === 'earnings') {
    body = '<div class="aff-stats n4">' + st('Lifetime earnings', money(A.lifetime), 'flat 20%', 'up') + st('Revenue you generated', money(A.net), 'net to Tradr') + st('Pending payout', money(A.pending), 'next: ' + A.payoutSettings.next) + st('Paid out', money(A.paid), 'lifetime') + '</div>' +
      '<div class="aff-grid2">' + earningsCard() + '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Payout settings</div></div><div class="aff-set"><div class="aff-set-r"><span>Commission rate</span><b>20% flat · lifetime</b></div><div class="aff-set-r"><span>Payout method</span><b>' + A.payoutSettings.method + '</b></div><div class="aff-set-r"><span>Minimum threshold</span><b>' + money(A.payoutSettings.threshold) + '</b></div><div class="aff-set-r"><span>Schedule</span><b>' + A.payoutSettings.schedule + '</b></div><button class="aff-sh" data-toast="Payout settings opened" style="margin-top:12px">Edit payout settings</button></div></div></div>' +
      '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Payouts</div><button class="aff-copy" data-toast="Withdrawal requested · paid within 3 working days">Withdraw ' + money(A.pending) + '</button></div><table class="aff-tab"><thead><tr><th>Date</th><th>Method</th><th class="r">Amount</th><th class="r">Status</th></tr></thead><tbody>' + A.payouts.map((p) => '<tr><td>' + p.date + '</td><td class="dim">' + p.method + '</td><td class="r mono">' + money(p.amt) + '</td><td class="r"><span class="aff-pill ' + (p.status === 'paid' ? 'on' : 'tr') + '">' + (p.status === 'paid' ? 'Paid' : 'Pending') + '</span></td></tr>').join('') + '</tbody></table></div>'
  } else if (tab === 'assets') {
    body = '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Your links & campaign codes</div><button class="aff-sh" data-toast="New campaign code created">+ New code</button></div><table class="aff-tab"><thead><tr><th>Campaign</th><th>Code</th><th class="r">Clicks</th><th class="r">Signups</th><th class="r">Conv.</th><th class="r"></th></tr></thead><tbody>' + A.campaigns.map((c) => '<tr><td>' + c.name + '</td><td class="mono">' + c.code + '</td><td class="r mono">' + c.clicks.toLocaleString() + '</td><td class="r mono">' + c.signups + '</td><td class="r mono">' + (c.signups / c.clicks * 100).toFixed(1) + '%</td><td class="r"><button class="tmpx-b" data-affcopy>Copy</button></td></tr>').join('') + '</tbody></table></div>' +
      '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Creative library</div></div><div class="asset-grid">' + A.assets.map((a) => '<div class="asset"><div class="asset-ic">' + a.ic + '</div><div class="asset-n">' + a.n + '</div><div class="asset-m dim">' + a.m + '</div><button class="aff-sh" data-toast="' + a.n + ' downloaded">Download</button></div>').join('') + '</div></div>' +
      '<div class="aff-card"><div class="aff-card-h"><div class="aff-card-t">Swipe copy</div><button class="aff-sh" data-affcopy>Copy all</button></div><div class="swipe">' + A.swipe.map((x) => '<div class="swipe-r">“' + x + '”</div>').join('') + '</div></div>'
  } else {
    body = '<div class="aff-stats">' + st('Lifetime earnings', money(A.lifetime), 'flat 20%', 'up') + st('This month', money(A.thisMonth), '+' + (((A.earn[11] - A.earn[10]) / A.earn[10]) * 100).toFixed(0) + '% vs last') + st('Pending payout', money(A.pending), 'next: ' + A.payoutSettings.next) + st('Active players', A.active + '', 'of ' + A.signups + ' signed up') + st('Their winnings', money(A.clientWon), 'won in comps', 'up') + st('Revenue generated', money(A.net), 'net to Tradr') + st('Conversion', conv.toFixed(1) + '%', A.clicks.toLocaleString() + ' clicks') + st('Churned', A.churned + '', 'win them back') + '</div>' +
      '<div class="aff-grid2">' + earningsCard() + milestonesCard() + '</div>' + funnel()
  }
  return '<div class="aff">' + hero + tabbar + body + '<div class="aff-note">Commission is a flat 20% of Tradr’s net revenue per referred client, paid monthly while active. Promoting Tradr means following our Partner Terms and financial-promotion rules — figures shown are a demo on a virtual account.</div></div>'
}
